# -----------------------------------------------------------------------------
#
#
# -----------------------------------------------------------------------------

makefile_build:
	rm -rf build && mkdir build && cd build && cmake .. && cd ..

clean:
	rm -rf build CMakeLists.txt.user
